import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for PMMSherpa, operated by DBAR LLC.',
}

const EFFECTIVE_DATE = 'April 22, 2026'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-[#111418] text-[#191c1e] dark:text-[#e2e4e8]">
      <header className="border-b border-[#f0f2f5] dark:border-[#2a2d32]">
        <div className="max-w-3xl mx-auto px-5 md:px-8 py-5 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md bg-gradient-to-br from-[#0058be] to-[#2170e4]" />
            <span className="font-medium">PMMSherpa</span>
          </Link>
          <Link href="/" className="text-sm text-muted-foreground hover:text-foreground">
            &larr; Back to home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-5 md:px-8 py-10 md:py-14">
        <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Effective: {EFFECTIVE_DATE}</p>

        <div className="space-y-8 text-[15px] leading-relaxed text-[#3f4246] dark:text-[#c7cad0]">
          <section>
            <p>
              These Terms of Service (&ldquo;<strong>Terms</strong>&rdquo;) govern your access to and use of
              PMMSherpa (the &ldquo;<strong>Service</strong>&rdquo;), operated by <strong>DBAR LLC</strong>, a Washington
              limited liability company doing business as &ldquo;PMMSHERPA&rdquo; (&ldquo;<strong>we</strong>,&rdquo; &ldquo;<strong>us</strong>,&rdquo;
              or &ldquo;<strong>our</strong>&rdquo;). By creating an account or using the Service, you agree to these
              Terms. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">1. The Service</h2>
            <p>
              PMMSherpa is an AI-powered product marketing assistant. It uses large language models together
              with a curated knowledge base and web research tools to help you with positioning, messaging,
              go-to-market strategy, competitive analysis, and related product marketing work. Outputs are
              generated by AI and may contain errors, omissions, or out-of-date information. PMMSherpa is
              provided as an informational and productivity tool, not professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">2. Eligibility and Accounts</h2>
            <p>
              You must be at least 18 years old and able to enter into a binding contract to use the Service.
              You are responsible for the accuracy of information you provide during signup (including your
              LinkedIn URL), for maintaining the security of your credentials, and for all activity that occurs
              under your account. Notify us immediately at{' '}
              <a href="mailto:support@pmmsherpa.com" className="text-[#0058be] dark:text-[#a8c0f0] hover:underline">
                support@pmmsherpa.com
              </a>{' '}
              if you suspect unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">3. Plans, Billing, and Cancellation</h2>
            <p className="mb-3">
              PMMSherpa offers a Free plan with a limited number of messages per month and paid plans with
              expanded usage. Current pricing and usage limits are shown at signup and on our pricing page and
              may change with notice.
            </p>
            <p className="mb-3">
              Paid subscriptions are billed in advance on a recurring basis by our payment processor, Stripe.
              By subscribing, you authorize us (through Stripe) to charge your payment method at the then-current
              rate, plus applicable taxes, at the start of each billing period until you cancel.
            </p>
            <p className="mb-3">
              You can cancel at any time from your account settings or via the Stripe customer portal. Cancellation
              takes effect at the end of the current billing period; you retain access until then. Fees already
              paid are non-refundable except where required by law. If you believe you were billed in error,
              email{' '}
              <a href="mailto:support@pmmsherpa.com" className="text-[#0058be] dark:text-[#a8c0f0] hover:underline">
                support@pmmsherpa.com
              </a>{' '}
              within 30 days and we will review in good faith.
            </p>
            <p>
              Usage limits (such as monthly message caps) are enforced per billing period. We may suspend or
              throttle accounts that materially exceed plan limits, abuse the Service, or create risk for other
              users.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the Service to violate any law or third-party right, or to generate unlawful, defamatory, harassing, infringing, or sexually exploitative content.</li>
              <li>Attempt to reverse-engineer, decompile, extract, or replicate the Service, its prompts, its knowledge base, or its underlying models.</li>
              <li>Use automated means (scrapers, bots, or headless browsers) to access the Service outside of documented interfaces, or to generate load beyond normal human use.</li>
              <li>Probe, scan, or bypass authentication, rate limits, or security measures.</li>
              <li>Resell, sublicense, or provide the Service to third parties as a competing product, or use the Service to build or train a competing AI product.</li>
              <li>Submit content containing malware, exploits, or material you do not have the right to share.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">5. Your Content</h2>
            <p className="mb-3">
              &ldquo;<strong>Your Content</strong>&rdquo; means the messages, files, URLs, and other materials you submit
              to the Service, together with the outputs generated for you in response. You retain ownership of
              Your Content. You grant us a limited, worldwide, non-exclusive license to host, process, and display
              Your Content solely to provide and improve the Service for you.
            </p>
            <p>
              <strong>We do not use Your Content to train third-party foundation models.</strong> Our AI providers
              (such as Anthropic, Google, and OpenAI) process Your Content on our behalf under their API terms,
              which do not grant them the right to train their models on your inputs or outputs. We may use
              aggregated, de-identified usage data to operate, secure, and improve the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">6. Our Intellectual Property</h2>
            <p>
              The Service, including its software, knowledge base, design, prompts, and documentation, is owned
              by DBAR LLC and its licensors and is protected by intellectual property laws. Except for the limited
              right to use the Service under these Terms, no rights are granted to you.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">7. AI Output Disclaimer</h2>
            <p>
              Outputs are generated by AI and may be inaccurate, incomplete, biased, or out of date. Different
              users may receive similar outputs for similar queries. You are responsible for reviewing and verifying
              any output before relying on it, and for ensuring that your use of any output complies with applicable
              law and does not infringe third-party rights. The Service is not a substitute for professional legal,
              financial, or other advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">8. Third-Party Services</h2>
            <p>
              The Service relies on third-party providers for authentication, payments, AI model access, email,
              analytics, and web research. Your use of the Service is also subject to those providers&rsquo; terms
              where applicable. See our{' '}
              <Link href="/privacy" className="text-[#0058be] dark:text-[#a8c0f0] hover:underline">
                Privacy Policy
              </Link>{' '}
              for the list of sub-processors.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">9. Warranty Disclaimer</h2>
            <p className="uppercase text-sm tracking-wide">
              The Service is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without warranties of any kind,
              whether express or implied, including warranties of merchantability, fitness for a particular
              purpose, non-infringement, or accuracy of output. We do not warrant that the Service will be
              uninterrupted, secure, or error-free.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">10. Limitation of Liability</h2>
            <p className="mb-3">
              To the maximum extent permitted by law, DBAR LLC and its officers, members, and employees will not
              be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or
              for any loss of profits, revenue, data, or goodwill, arising out of or related to the Service, even
              if advised of the possibility of such damages.
            </p>
            <p>
              Our total cumulative liability for all claims arising out of or related to the Service or these
              Terms will not exceed the greater of (a) the amount you paid us in the twelve (12) months before
              the event giving rise to liability, or (b) one hundred U.S. dollars ($100).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">11. Indemnification</h2>
            <p>
              You will defend, indemnify, and hold harmless DBAR LLC from any third-party claim arising from your
              breach of these Terms, your misuse of the Service, or Your Content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">12. Termination</h2>
            <p>
              You may stop using the Service and delete your account at any time. We may suspend or terminate
              your access if you violate these Terms, abuse the Service, or for legal, security, or operational
              reasons. Sections intended to survive termination (including IP, disclaimers, liability limits, and
              governing law) will survive.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">13. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. If changes are material, we will notify you by email
              or in-product notice. Your continued use of the Service after the effective date of updated Terms
              constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">14. Governing Law and Disputes</h2>
            <p className="mb-3">
              These Terms are governed by the laws of the State of Washington, U.S.A., without regard to conflict
              of laws principles. Any dispute arising out of or related to these Terms or the Service will be
              resolved exclusively in the state or federal courts located in King County, Washington, and you
              consent to personal jurisdiction there.
            </p>
            <p>
              Each party waives any right to a jury trial. Class actions and class-wide arbitrations are not
              permitted.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#191c1e] dark:text-[#e2e4e8] mb-3">15. Contact</h2>
            <p>
              Questions about these Terms? Email{' '}
              <a href="mailto:support@pmmsherpa.com" className="text-[#0058be] dark:text-[#a8c0f0] hover:underline">
                support@pmmsherpa.com
              </a>
              .
            </p>
            <p className="mt-3 text-sm text-muted-foreground">
              DBAR LLC d/b/a PMMSHERPA &middot; State of Washington, U.S.A.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-[#f0f2f5] dark:border-[#2a2d32] flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted-foreground">
          <Link href="/privacy" className="hover:text-foreground">Privacy Policy</Link>
          <a href="mailto:support@pmmsherpa.com" className="hover:text-foreground">Contact Us</a>
          <Link href="/" className="hover:text-foreground">Home</Link>
        </div>
      </main>
    </div>
  )
}
